language: php
php:
  - '7.2'
  - '7.3'

install:
  - composer install --no-interaction

before_script:
  - git fetch --unshallow
  - mkdir -p build/logs
  - phpenv config-add <(echo "memory_limit = 2G")

script:
  - composer run-script lint
  - composer run-script test

after_success:
  - travis_retry php vendor/bin/php-coveralls

notifications:
  email: false
